### ISSUE TITLE
有一些类找不到

### ISSUE THREAD

**Issue by Leao-lucky** [pepsimaxin/AOSP_Launcher3_Gradle#1]
大佬你好，我拉了代码，还有一些android的类和变量找不到，请问是还没有完全适配好AS编译嘛？这些类要引用的jar包，我要去哪里找，是要根据bp文件，去AOSP源码里面自己编译嘛？

**Comment by pepsimaxin** [comment]
> 大佬你好，我拉了代码，还有一些android的类和变量找不到，请问是还没有完全适配好AS编译嘛？这些类要引用的jar包，我要去哪里找，是要根据bp文件，去AOSP源码里面自己编译嘛？

将附件解压， android.jar 替换到你的 sdk（比如34）里面即可

**Comment by Leao-lucky** [comment]
> > 大佬你好，我拉了代码，还有一些android的类和变量找不到，请问是还没有完全适配好AS编译嘛？这些类要引用的jar包，我要去哪里找，是要根据bp文件，去AOSP源码里面自己编译嘛？
> 
> 将附件解压， android.jar 替换到你的 sdk（比如34）里面即可

感谢大佬回复，请问附件放到哪里了，没有找到。。

**Comment by pepsimaxin** [comment]
> > > 大佬你好，我拉了代码，还有一些android的类和变量找不到，请问是还没有完全适配好AS编译嘛？这些类要引用的jar包，我要去哪里找，是要根据bp文件，去AOSP源码里面自己编译嘛？
> > 
> > 
> > 将附件解压， android.jar 替换到你的 sdk（比如34）里面即可
> 
> 感谢大佬回复，请问附件放到哪里了，没有找到。。

sorry，没注意，压缩包太大了，没传上去，给你个百度链接

通过网盘分享的文件：android.jar_android_14
链接: https://pan.baidu.com/s/1ruxQHvjcpSijI47xHRKK0w?pwd=6heh 提取码: 6heh 
--来自百度网盘超级会员v6的分享

**Comment by Leao-lucky** [comment]
> > > > 大佬你好，我拉了代码，还有一些android的类和变量找不到，请问是还没有完全适配好AS编译嘛？这些类要引用的jar包，我要去哪里找，是要根据bp文件，去AOSP源码里面自己编译嘛？
> > > 
> > > 
> > > 将附件解压， android.jar 替换到你的 sdk（比如34）里面即可
> > 
> > 
> > 感谢大佬回复，请问附件放到哪里了，没有找到。。
> 
> sorry，没注意，压缩包太大了，没传上去，给你个百度链接
> 
> 通过网盘分享的文件：android.jar_android_14 链接: https://pan.baidu.com/s/1ruxQHvjcpSijI47xHRKK0w?pwd=6heh 提取码: 6heh --来自百度网盘超级会员v6的分享

好的，非常感谢，编译成功了

**Comment by Abvatous** [comment]
up 大大，这个

> > > > 大佬你好，我拉了代码，还有一些android的类和变量找不到，请问是还没有完全适配好AS编译嘛？这些类要引用的jar包，我要去哪里找，是要根据bp文件，去AOSP源码里面自己编译嘛？
> > > 
> > > 
> > > 将附件解压， android.jar 替换到你的 sdk（比如34）里面即可
> > 
> > 
> > 感谢大佬回复，请问附件放到哪里了，没有找到。。
> 
> sorry，没注意，压缩包太大了，没传上去，给你个百度链接
> 
> 通过网盘分享的文件：android.jar_android_14 链接: https://pan.baidu.com/s/1ruxQHvjcpSijI47xHRKK0w?pwd=6heh 提取码: 6heh --来自百度网盘超级会员v6的分享

up 大大，这个 android.jar 能重新分享下嘛？谢谢啦

**Comment by Abvatous** [comment]
谢谢大大的帮助，可以啦~

> up 大大，这个
> 
> > > > > 大佬你好，我拉了代码，还有一些android的类和变量找不到，请问是还没有完全适配好AS编译嘛？这些类要引用的jar包，我要去哪里找，是要根据bp文件，去AOSP源码里面自己编译嘛？
> > > > 
> > > > 
> > > > 将附件解压， android.jar 替换到你的 sdk（比如34）里面即可
> > > 
> > > 
> > > 感谢大佬回复，请问附件放到哪里了，没有找到。。
> > 
> > 
> > sorry，没注意，压缩包太大了，没传上去，给你个百度链接
> > 通过网盘分享的文件：android.jar_android_14 链接: https://pan.baidu.com/s/1ruxQHvjcpSijI47xHRKK0w?pwd=6heh 提取码: 6heh --来自百度网盘超级会员v6的分享
> 
> up 大大，这个 android.jar 能重新分享下嘛？谢谢啦

谢谢大大的帮助，可以啦~
